### PR TITLE
Added a few assets to the game

### PR DESCRIPTION
**Pull request by Nireves333**
As the title says, check it out to see if it works for you guys!

### CODE REVIEW

**Review by ggorlen — CHANGES_REQUESTED** [review]
Nice. I like the art style!

Do we have box-on-goal and player-on-goal images? Without those it's pretty hard to tell which boxes are completed and which aren't, and whether the player is standing on a goal or not.

We can rotate the player to face different directions, but in the meantime we might want to consder a forward-facing player icon that doesn't need rotation, like in https://en.wikipedia.org/wiki/Sokoban#/media/File:Sokoban_ani.gif

**Comment by Nireves333** [comment]
I added a payer on a goal and the same for boxes. For now, is it okay to keep the robot player as is? I consider all of the current assets placeholders for testing purposes, for now, unless someone wants to make a flat-facing character right now.

**Review by ggorlen — COMMENTED** [review]
This seems fine, although do we want a goal square image too? We can use the plain ASCII `.` character for now though, but since we'll eventually be all-images, we might as well toss one in. I forgot to mention that in the last review -- sorry.

Since these images are for prototyping, don't worry about being super-detailed. We just want to feel out the size, style and use something more attractive and easier to play than ASCII.

**Review by itancio — CHANGES_REQUESTED** [review]
WALL: I think that we need more contrast between the wall and the floor. The wall can be darker and have a more pronounced pattern.

BOX ON GOAL: I can't quite see the difference between a box and a box on goal.

Will the player float on top of the floor? or are we swapping images as the player moves? Can we see a mockup of what the board would look like with all of these elements? I think that creating more contrast between the wall and floor can help differentiate the barrier and a walkable path.

**Comment by ggorlen** [comment]
These are all great questions we'll need to consider as we move forward with the UI. As with any game, playing a few different implementations will give us a flavor of the "normal" designs. Doing an image search can also show a lot of typical UIs, but it might not clearly communicate some of the nuances that Irvin brought up.

> Will the player float on top of the floor? or are we swapping images as the player moves? 

I suggest baking the floor and goal patterns below the player, so we have 2 separate player images and separate images. One tile per tile. It's simpler technically and I don't see any advantage to doing it another way.

As a possible stretch goal, we could do some extra work in the renderer to figure out which angles comprise the walls so they look continuous with a single outline rather than tiles, like [this example](https://images-na.ssl-images-amazon.com/images/I/81U3HFRObwL.png).

**Review by jrange10 — APPROVED** [review]
I like the color schemes. Maybe change the color of the goal box when it reaches objective. Good job.

**Comment by ggorlen** [comment]
After the update, I'm confused about why we're adding +298 lines across 14 files.

**Pull request merged**
